title: Earth
public: /www
parses:
    - build/portal/.env.dist
    - build/portal/.npmrc.dist
scripts:
    - cp build/portal/.env.dist .env
    - cp build/portal/.npmrc.dist .npmrc
    - composer install
    - php windwalker run preparedev
